server:
    port: 8085
    
spring:
    application:
        name: AssetsPerson
    data:
        mongodb:
            uri: mongodb+srv://aburgoss:aburgoss@cluster0.ibhoc.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8082/eureka/           
