#dbname: AssetsPersonDB
#dbport: 27017
spring:
    data:
        mongodb:
          uri: mongodb+srv://Burgos:<aburgoss123456>@cluster0.ibhoc.mongodb.net/AssetsPersonDB?retryWrites=true&w=majority
          database: AssetsPersonDB
server:
    port: 8085
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8082/eureka/
