server:
    port: 8085
spring:
    data:
        mongodb:
            uri: mongodb+srv://Burgos:aburgos123456@cluster0.ibhoc.mongodb.net/AssetsPersonDB?retryWrites=true&w=majority
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8082/eureka/
